<a href="https://colab.research.google.com/github/34maksuda/Pytorch-Tutorial-Youtube/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Tensors
A torch.tensor is a multi-dimensional matrix containing elements of a single data type.
--Similar to numpy arrays, but full of fun of things that make them work better on GPU's(vs regular CPU's)
--default data type of float32
--More suitable fro deep learning than a numpy array

In [3]:
import torch
import numpy as np

##Lists

In [1]:
my_list =[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

#Numpy Arrays

In [8]:
np1 = np.random.rand(3,4)
np1

array([[0.86538727, 0.7753837 , 0.62325763, 0.314417  ],
       [0.76629462, 0.94346259, 0.67614037, 0.24586037],
       [0.86696769, 0.37759607, 0.40795443, 0.37218212]])

In [6]:
np1.dtype

dtype('float64')

##Tensors


In [10]:
tensor_2d = torch.randn(3)
tensor_2d

tensor([-1.3063, -0.2734, -0.4558])

In [11]:
tensor_2d.dtype

torch.float32

In [16]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [19]:
#create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8654, 0.7754, 0.6233, 0.3144],
        [0.7663, 0.9435, 0.6761, 0.2459],
        [0.8670, 0.3776, 0.4080, 0.3722]], dtype=torch.float64)

##Tensor Operations

In [27]:
my_torch = torch.arange(12)
my_torch


tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
#Reshape and View
my_torch = my_torch.reshape(4, 3)
my_torch

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])

In [34]:
#Reshape if we don't know the number of items using -1
my_torch2 = my_torch.reshape(-1,3)#jetar(row/column) er dimensipn jana thakbena seta te -1 dte hbe
my_torch3 = my_torch.reshape(3, -1)
print(my_torch2)
print(my_torch3)

tensor([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [39]:
my_torch4 = my_torch.view(3,-1)
my_torch4

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [45]:
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
my_torch6 = my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [48]:
my_torch5[1] = 4050
my_torch5

tensor([   0, 4050,    2,    3,    4,    5,    6,    7,    8,    9])

In [49]:
my_torch6

tensor([[   0, 4050,    2,    3,    4],
        [   5,    6,    7,    8,    9]])

In [53]:
#slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
my_torch7[7] #specific item number 7 dekhabe

tensor(7)

In [57]:
my_torchB = my_torch7.reshape(5,2)
my_torchB

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [59]:
my_torchB[:, 1]

tensor([1, 3, 5, 7, 9])

In [60]:
my_torchB[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])

##Math Operation using tensors

In [1]:
import torch
import numpy as np

In [4]:
tensor_a = torch.tensor([1, 2, 3,4])
tensor_b = torch.tensor([5, 6, 7, 8])

In [5]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [6]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [7]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [8]:
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [9]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [10]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [14]:
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [16]:
#Modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [18]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [19]:
#Exponen
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [20]:
tensor_a = tensor_b
tensor_a

tensor([5, 6, 7, 8])

In [21]:
tensor_a

tensor([5, 6, 7, 8])

In [22]:
tensor_a = tensor_a + tensor_b
tensor_a

tensor([10, 12, 14, 16])