<a href="https://colab.research.google.com/github/34maksuda/Pytorch-Tutorial-Youtube/blob/main/Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##Tensors
A torch.tensor is a multi-dimensional matrix containing elements of a single data type.
--Similar to numpy arrays, but full of fun of things that make them work better on GPU's(vs regular CPU's)
--default data type of float32
--More suitable fro deep learning than a numpy array

In [3]:
import torch
import numpy as np

##Lists

In [1]:
my_list =[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

#Numpy Arrays

In [8]:
np1 = np.random.rand(3,4)
np1

array([[0.86538727, 0.7753837 , 0.62325763, 0.314417  ],
       [0.76629462, 0.94346259, 0.67614037, 0.24586037],
       [0.86696769, 0.37759607, 0.40795443, 0.37218212]])

In [6]:
np1.dtype

dtype('float64')

##Tensors


In [10]:
tensor_2d = torch.randn(3)
tensor_2d

tensor([-1.3063, -0.2734, -0.4558])

In [11]:
tensor_2d.dtype

torch.float32

In [16]:
tensor_3d = torch.zeros(2, 3, 4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [19]:
#create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.8654, 0.7754, 0.6233, 0.3144],
        [0.7663, 0.9435, 0.6761, 0.2459],
        [0.8670, 0.3776, 0.4080, 0.3722]], dtype=torch.float64)